apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: node-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: node-exporter
        image: {{ .Values.images.node_exporter }}
        args:
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --no-collector.wifi
        volumeMounts:
        - name: rootfs
          readOnly: true
          mountPath: /host/root
        - name: sysfs
          readOnly: true
          mountPath: /host/sys
        ports:
        - containerPort: {{ .Values.node_exporter.containerPort }}
          protocol: TCP
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: sysfs
        hostPath:
          path: /sys
