apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
    - job_name: node_exporter
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: {{ .Release.Name }}-node-exporter
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_node_name]
        target_label: node_name
        action: replace
