apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Release.Name }}-node-exporter-rule
  namespace: monitoring
data:
  rule_node_exporter.yaml: |
    groups:
    - name: node_exporter
      rules:
      - alert: node_high_cpu
        expr: "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode='idle'}[1m]) * 100)) >= 80"
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on {{ `{{ $labels.instance }}` }}"
          description: "CPU usage is at {{ `{{ printf \"%.2f\" $value }}` }}"
      - alert: memory_high_usage
        expr: "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 >= 70"
        for: 2m
        labels:
          severity: medium
        annotations:
          summary: "High memory usage on {{ `{{ $labels.instance }}` }}"
          description: "Memory usage is at {{ `{{ printf \"%.2f\" $value }}` }}"
