apiVersion: v1
kind: ServiceAccount 
metadata:
  name: {{ .Release.Name }}-prometheus-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-prometheus-sa-role
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-prometheus-sa-rb
  namespace: monitoring
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-prometheus-sa-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ .Release.Name }}-prometheus-sa
  namespace: monitoring
