apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name}}-prometheus
  namespace: monitoring
spec:
  rules:
  - host: {{ .Values.prometheus.ingress_host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-prometheus
            port:
              number: {{ .Values.prometheus.servicePort }}
